### User sign up endpoint
POST http://localhost:3001/user/create
Content-Type: application/json

{
    "name": "Test",
    "phone": 1234567,
    "email": "test1011@test.com",
    "password":"Test2222!"
}

### User sign in endpoint
POST http://localhost:3001/user/login
Content-Type: application/json

{
     "email": "test1011@test.com",
    "password":"Test2222!"
}

### Get user profile endpoint
GET http://localhost:3001/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI2MTI2MzgzLCJleHAiOjE2MjYxMjcyODN9.Ev-OWsHeQMlMUAUfGzfjBSPXqFEXifMeBJygUT_04ys

### Token Routers

### Get refresh token
GET http://localhost:3001/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI1MTg3Nzg2LCJleHAiOjE2Mjc3Nzk3ODZ9.IdDBd_fo8PlUFwF-H5VrHF4ee5KtP6XF6Ch34fODs54


### Password reset request endpoint
POST http://localhost:3001/user/reset-password
Content-Type: application/json

{
    "email": "test1011@test.com"
}

### Update password endpoint
PATCH http://localhost:3001/user/reset-password
Content-Type: application/json

{
    "email": "test1011@test.com",
    "pin": 148336,
    "newPassword":"pass123"
}

### Logout endpoint
DELETE http://localhost:3001/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI1MTg3Nzg2LCJleHAiOjE2MjUxODg2ODZ9.Oj7ogSPa7vrjjNJshln_j4ELnlHK9A1gNLNJ09FMmAs
