### User sign up endpoint
POST http://localhost:3001/user/create
Content-Type: application/json

{
    "name": "Test",
    "phone": 1234567,
    "email": "test1011@test.com",
    "password":"Test2222!"
}

### User sign in endpoint
POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email": "test1011@test.com",
    "password":"pass123"
}

### Get user profile endpoint
GET http://localhost:3001/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI1MTA2ODU3LCJleHAiOjE2MjUxMDc3NTd9.q1AeK6EPPlQLsL9PsOjtQUcqaKFUzhoPVO1c7C3M5MY

### Token Routers

### Get refresh token
GET http://localhost:3001/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI1MTA2ODU3LCJleHAiOjE2Mjc2OTg4NTd9.0DcnXiU6OEKPlJ3a_mGemaBDv-_rImDdLtHiZ05xZS8


### Password reset request endpoint
POST http://localhost:3001/user/reset-password
Content-Type: application/json

{
    "email": "test1011@test.com"
}

### Update password endpoint
PATCH http://localhost:3001/user/reset-password
Content-Type: application/json

{
    "email": "test1011@test.com",
    "pin": 187894,
    "newPassword":"pass123"
}

### Logout endpoint
DELETE http://localhost:3001/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI1MTA5MDgxLCJleHAiOjE2MjUxMDk5ODF9.ZRbItTfMlDQAEGGUFGwfK2jMbwX5WY5KmbxFogWBbUc
