### User sign up endpoint
POST http://localhost:3001/user/create
Content-Type: application/json

{
    "name": "Test",
    "phone": 1234567,
    "email": "test1011@test.com",
    "password":"Test2222!"
}

### User sign in endpoint
POST http://localhost:3001/user/login
Content-Type: application/json

{
     "email": "test1011@test.com",
    "password":"Test2222!"
}

### Get user profile endpoint
GET http://localhost:3001/user
Authorization: 

### Token Routers

### Get refresh token
GET http://localhost:3001/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI2NDU3NzE4LCJleHAiOjE2MjkwNDk3MTh9.DOyw1pIN0tSn_Jt87kXCKeByuFTF5MfEZzp0SZR4N8g


### Password reset request endpoint
POST http://localhost:3001/user/reset-password
Content-Type: application/json

{
    "email": "test1011@test.com"
}

### Update password endpoint
PATCH http://localhost:3001/user/reset-password
Content-Type: application/json

{
    "email": "test1011@test.com",
    "pin": 148336,
    "newPassword":"pass123"
}

### Logout endpoint
DELETE http://localhost:3001/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI2NDYzMTc4LCJleHAiOjE2MjY0NjQwNzh9.708L6faUu7fWNnOiYHjbgkQg2jT1VlcyqGGhxxkZGQg


### Unit Routers
### Get a single unit 
GET http://localhost:3001/units/unit/60df8443aa2988e9d5a51204
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMDExQHRlc3QuY29tIiwiaWF0IjoxNjI2NDYzMTc4LCJleHAiOjE

### Gets all units
GET http://localhost:3001/units/60df8443aa2988e9d5a51204
Authorization: : 

### Creates new unit
POST http://localhost:3001/units/
Authorization: 
Content-Type: application/json

{
    "unitAddedBy": "Cody Usher",
    "unitNum" : "A901",
    "cleanStatus": true,
    "inHouseStatus": true,
    "managedStatus": true,
    "rentalStatus" : true,
    "note": "this is a note",
    "noteAddedBy": "Cody Usher",
    "noteStatus": true,
    "prefAddedBy": "Cody Usher",
    "pref": "80 Degrees"
}

### Creates a new note
PUT http://localhost:3001/units/unit/note/60df8443aa2988e9d5a51204
Authorization: 
Content-Type: application/json
{
    "note": "this is a pref number 7",
    "noteAddedBy": "jack"
}

### Updates note status
PATCH http://localhost:3001/unit/note-status/60f35b0466957a8c0cdec48e

### Removes done note
PATCH http://localhost:3001/unit/note/60f35b0466957a8c0cdec48e

### Creates a new pref
PUT http://localhost:3001/units/unit/prefs/60df8443aa2988e9d5a51204
Authorization: 
Content-Type: application/json
{
    "pref": "this is a pref number 7",
    "prefAddedBy": "jack"
}

